# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_mergebamsR_wrappers", use_symbols = TRUE, package_name = "mergebamsR")

#' @docType package
#' @usage NULL
#' @useDynLib mergebamsR, .registration = TRUE
NULL

#' mergebams_rust
#' @export
#' @keywords internal
mergebams_rust_helper <- function(bams, out_path, names, prefixes) invisible(.Call(wrap__mergebams_rust_helper, bams, out_path, names, prefixes))


# nolint end
