# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_mergebamsR_wrappers", use_symbols = TRUE, package_name = "mergebamsR")

#' @docType package
#' @usage NULL
#' @useDynLib mergebamsR, .registration = TRUE
NULL

#' mergebams_rust
#' @export
#' @keywords internal
mergebams_rust_helper <- function(bams, out_path, names, prefixes) invisible(.Call(wrap__mergebams_rust_helper, bams, out_path, names, prefixes))

#' peekbam_rust
#' @export
#' @keywords internal
peekbam_rust_helper <- function(bam, n, field, tag) .Call(wrap__peekbam_rust_helper, bam, n, field, tag)

#' subsetbam_rust
#' @export
#' @keywords internal
subsetbam_rust_helper <- function(inputbam, features, outputbams, tag, cores, field, dump_bam) invisible(.Call(wrap__subsetbam_rust_helper, inputbam, features, outputbams, tag, cores, field, dump_bam))


# nolint end
